### ISSUE TITLE
邮件不提醒

### ISSUE THREAD

**Issue by iwyang** [discussjs/discuss#13]
```
服务端地址：https://xxxxxx.vercel.app

服务商主机：smtp.qq.com

服务商主机端口：465

发件人：455343442@qq.com

授权码：xxxxxxxxxxx
```
是不是哪里出了问题

**Comment by lete114** [comment]
正确的，你是不是用的管理员邮箱评论的？
管理员评论不会邮件通知

**Comment by iwyang** [comment]
> 正确的，你是不是用的管理员邮箱评论的？ 管理员评论不会邮件通知

换了一个邮箱，还是不行

**Comment by lete114** [comment]
> 换了一个邮箱，还是不行

你评论的时候看一下vercel的函数控制台日志

**Comment by iwyang** [comment]
> > 换了一个邮箱，还是不行
> 
> 你评论的时候看一下vercel的函数控制台日志

```
🐞 
/var/task/node_modules/discuss/src/server/router/router.js
:
30
body {
  type: 'COMMIT_COMMENT',
  nick: 'iwyang',
  mail: 'iwyang@qq.com',
  site: '',
  content: '测试一下下',
  path: '#62e73dcfed082c10952f674e',
  pid: '',
  rid: '',
  ua: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36',
  ip: '104.224.191.88'
}
Token exception
🐞 
/var/task/node_modules/discuss/src/server/utils/akismet.js
:
13
Not Set Akismet
🐞 
/var/task/node_modules/discuss/src/server/utils/commentUtils.js
:
111
2022-08-01T03:49:48.905Z	54ef1f2b-89e4-413e-9241-0ed7d961dd1f	ERROR	Mail ERROR: Mail configuration information error cancel sending emails
🐞 
/var/task/node_modules/discuss/src/server/utils/commentUtils.js
:
112
2022-08-01T03:49:48.905Z	54ef1f2b-89e4-413e-9241-0ed7d961dd1f	ERROR	Error: Parameter 'masterSubject' not legal
    at VerifyParams (/var/task/node_modules/discuss/src/server/utils/verify.js:9:13)
    at SendMailHandler (/var/task/node_modules/discuss/src/server/utils/commentUtils.js:89:5)
    at CommitComment (/var/task/node_modules/discuss/src/server/router/comment.js:124:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Router (/var/task/node_modules/discuss/src/server/router/router.js:78:21)
    at async module.exports (/var/task/node_modules/discuss/src/server/main.js:37:3)
    at async Server.<anonymous> (/var/task/___vc/__helpers.js:813:13)
```
```

**Comment by lete114** [comment]
你缺少了`masterSubject`邮件标题
![image](https://user-images.githubusercontent.com/48512251/182074832-058e64e0-86e1-4d9b-a3db-55a00f0c2d3e.png)

**Comment by iwyang** [comment]
谢谢
